version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          name: Create dynamic jobs
          config-path: .circleci/config.old.yml
          base-revision: next
          mapping: |
            .*\.[tj]s$ run-js true
