version: 2.1
setup: true

orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.0.3
  path-filtering: circleci/path-filtering@0.1.3
  node: circleci/node@5.0.3

jobs:
  setup:
    executor: continuation/default
    steps:
      - git-shallow-clone/checkout_advanced:
          clone_options: '--depth 1 --verbose'
      - node/install:
          node-version: '16.17'
      - path-filtering/filter:
          name: Create dynamic jobs
          mapping: |
            .*\.[tj]s$ run-js true
          config-path: .circleci/config.old.yml

workflows:
  setup:
    jobs:
      - setup